# Generated by Django 3.2.8 on 2021-10-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
