# Generated by Django 3.2.8 on 2021-10-27 08:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
