# Generated by Django 3.2.8 on 2021-10-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='post_date',
        ),
    ]
